### PR TITLE
Implement first part of BLS test vectors

### LINKED ISSUE #6: BLS test vectors
Ref: https://github.com/ethereum/py-evm/blob/master/eth/_utils/bls.py

- [ ] `aggregate_pubkeys(pubkeys: Sequence[int]) -> int`
- [ ] `verify(message: bytes, pubkey: int, signature: bytes, domain: int) -> bool`
- [ ] `verify_multiple(verify_multiple(pubkeys: Sequence[int], messages: Sequence[bytes], signature: bytes, domain: int) -> bool`

@mratsim Anything else I missed?

### PR DESCRIPTION
**Pull request by mratsim**
This implement the first part of BLS test vectors.

This tests:
 - `hash_to_G2` uncompressed (optional, helps to test G2 compression)
 - `hash_to_G2` compressed (which is the default)
 - Private key to public key
 - message signature
 - signature aggregation
 - public key aggregation

Missing:
  - Verification: it takes to long to generate on my (very powerful) PC so it's commented out. We probably should take a subset.
  - Aggregated verification
  - Proof of possession

The bls implementation is taken from Trinity as of commit https://github.com/ethereum/trinity/blob/fa370299106b6391e203e8945f44f09f2c9d8703/eth2/_utils/bls.py (the current one)

Format open to discussion cc @djrtwo, @hwwhww, @paulhauner, @cheatfate, @ChihChengLiang 
Closes #6

### CODE REVIEW

**Comment by hwwhww** [comment]
Great work @mratsim 👍 
The test format looks good to me.

FYI In python implementation, we will fix https://github.com/ethereum/trinity/issues/199 soooooon. I think it won't make yaml file be different since you already did the type conversion (`int_to_big_endian`, `big_endian_to_int`) in `tgen_bls.py`.

**Comment by mratsim** [comment]
Important: https://github.com/ethereum/eth2.0-specs/issues/508 needs to be clarified, currently `modular_squareroot` doesn't gives the same results as Milagro.

**Comment by djrtwo** [comment]
Does #13 supersede this PR?

**Comment by mratsim** [comment]
it does

**Pull request closed without merging**
