### PR TITLE
Regenerate shuffling tests updated to v0.4.0 spec

### PR DESCRIPTION
**Pull request by zilm13**
Matching latest generators https://github.com/ethereum/eth2.0-test-generators/tree/7a3358a8f09b5cae9358906b63ec1c333dc7d3cb

### CODE REVIEW

**Comment by ChihChengLiang** [comment]
Ahh... we kind of not doing the update manually.
@jannikluhn could we have a release for shuffling?

**Comment by zilm13** [comment]
@ChihChengLiang ahhh cool, but looks that there are no operating auto-trgiggers.

**Comment by ChihChengLiang** [comment]
Released v0.1.3 to reflect changes in this PR.
https://github.com/ethereum/eth2.0-test-generators/releases/tag/v0.1.3
The tests repo is designed to be updated when the generator is released.
Will explore some options of auto-trgiggers recently.

**Comment by ChihChengLiang** [comment]
Will manually release immediately every time a PR is merged for the time being. Let's move the auto-trigger discussion to #26.

**Pull request closed without merging**
